name: Build
on: [push, pull_request]

jobs:
  build-msvc:
    strategy:
      matrix:
        os: [windows-latest]
        toolset: ['14.39'] # VS 2019, 2017, and 2015 (see below)
        arch: [i386]
        config: [Release]
        dllver: ['0x600']
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
    - name: Install ninja
      run: choco install -y ninja
    - name: Install Flex & Bison
      run: |
        curl -O https://svn.reactos.org/storage/vperevertkin/flexbison.7z
        7z x flexbison.7z -O${{github.workspace}}\bin
        echo "${{github.workspace}}\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "BISON_PKGDATADIR=${{github.workspace}}\bin\share\bison" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "M4=${{github.workspace}}\bin\m4.exe" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
    - name: Activate VS cmd (x86)
      if: ${{ matrix.arch == 'i386' }}
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64_x86
        toolset: ${{matrix.toolset}}
    - name: Activate VS cmd (amd64)
      if: ${{ matrix.arch == 'amd64' }}
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64
        toolset: ${{matrix.toolset}}
    - name: Source checkout
      uses: actions/checkout@v4
      with:
        path: src
    - name: Configure
      run: cmake -S src -B build -G Ninja -DCMAKE_CXX_FLAGS="/O2i /fp:fast /GL /Gy /Gw /GF /Zf /MP" -DCMAKE_TOOLCHAIN_FILE:FILEPATH=toolchain-msvc.cmake -DARCH:STRING=${{matrix.arch}} -DCMAKE_BUILD_TYPE=${{matrix.config}} -DDLL_EXPORT_VERSION=${{matrix.dllver}} -DENABLE_ROSTESTS=1 -DENABLE_ROSAPPS=1
    - name: Build
      run: cmake --build build -- -k0
    - name: Generate ISOs
      run: cmake --build build --target bootcd
    - name: Upload ISOs
      uses: actions/upload-artifact@v4
      with:
        name: reactos-msvc${{matrix.toolset}}-${{matrix.arch}}-${{matrix.config}}-${{matrix.dllver}}-${{github.sha}}
        path: |
          build/bootcd.iso
          build/livecd.iso
    - name: Upload debug symbols
      if: ${{ matrix.config == 'Debug' }}
      uses: actions/upload-artifact@v4
      with:
        name: reactos-syms-msvc${{matrix.toolset}}-${{matrix.arch}}-${{matrix.config}}-${{matrix.dllver}}-${{github.sha}}
        path: build/msvc_pdb
